# Generated by Django 3.2.16 on 2022-12-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_use', models.DateTimeField(verbose_name='date of use')),
                ('amount', models.PositiveIntegerField(verbose_name='purchase amount')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='appling',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('activated', 'activated'), ('not activated', 'not activated'), ('overdue', 'overdue')], default='not activated', max_length=13),
        ),
        migrations.DeleteModel(
            name='Appling',
        ),
        migrations.AddField(
            model_name='applying',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applying', to='card.card', verbose_name='card usage'),
        ),
    ]
